title = "Qiqilike"

# 服务相关
[server]
  address = ":1999"

# 日志级别
[logger]
  level = "debug"

# 数据库相关
[database]
  driver = "mysql"
[mysql]
  host = "127.0.0.1"
  port = 5664
  name = "tieba"
  params = "parseTime=true&loc=Local"
  user = "root"
  pass = "kong"

# Redis相关
[redis]
  host = "127.0.0.1"
  port = 6379
  database = 0
  auth = ""

# kafka相关
[kafka]
  #host = "127.0.0.1"
  #port = "6379"

