title = "Qiqilike"

# 服务相关
[server]
  address = ":1999"

# API相关
[api]
  prefix = "/api/v1"

# 日志级别
[logger]
  level = "debug"

# 数据库相关
[database]
  driver = "mysql"
[mysql]
  addr = "127.0.0.1"
  port = 5664
  name = "tieba"
  params = "parseTime=true&loc=Local"
  user = "root"
  pass = "kongkong"

# Redis相关
[redis]
  addr = "127.0.0.1"
  port = 6379
  database = 0
  auth = ""
  maxIdle = 2
  maxActive = 15
  idleTimeout = 2000

# kafka相关
[kafka]
  #host = "127.0.0.1"

